### PR TITLE
Max port

### PR DESCRIPTION
**Pull request by klingklangklong**
Initial version of the Max/MSP port of the PD patch :)

The external can be found in max_port/externals/KlingKlangKlong.DDSP_realtime.mxo
An example usage can be found the help patch in max_port/help/KlingKlangKlong.DDSP_realtime.maxhelp

It works based on the following port of sigmund to Max: https://github.com/v7b1/sigmund_64bit-version

### CODE REVIEW

**Comment by caillonantoine** [comment]
thanks for the PR ! It seems that you included all the build files, and devkit from max, resulting in >10MB commits, which is not very convenient. Can you delete everything unecessary, such as `additional_files`, `build`, `docs`, `externals`, `projects/helloworld` `tests` and `tmp` ? min-api and min-lip should also be included as `submodules` to avoid redundancy !

**Comment by klingklangklong** [comment]
Sure thing, as you prefer! :) Everything should be in place now, let me know if everything is as expected!

**Comment by caillonantoine** [comment]
Thanks for the clean up! I'm gonna merge your PR in a feature branch and will test it today! :) Thanks again for your work! 👍

**Comment by JeremyKeenan** [comment]
Is this available as a release somewhere, or still a work in progress?

**Pull request merged**
